# Generated by Django 3.2.9 on 2021-11-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=13)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=13)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('km', models.DecimalField(blank=True, decimal_places=3, max_digits=7)),
                ('place', models.CharField(blank=True, max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=80)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=20)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('direction', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
