# Generated by Django 3.2.9 on 2021-11-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='poi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
