# Generated by Django 3.2.9 on 2021-11-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0003_poi_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='km',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='place',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
