# Generated by Django 3.2.9 on 2021-12-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0005_poi_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mapStyle', models.CharField(max_length=100)),
                ('centerLng', models.DecimalField(decimal_places=10, max_digits=13, null=True)),
                ('centerLat', models.DecimalField(decimal_places=10, max_digits=13, null=True)),
                ('zoom', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='poi',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='place',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
