# Generated by Django 3.2.9 on 2021-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0006_auto_20211203_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='centerLat',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='centerLng',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13),
        ),
    ]
